[build]
  publish = "."

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

[analytics]
  enabled = true

[context.production.environment]
  WHATSAPP_NUMBER = "263778105259"
  CONTACT_EMAIL = "build@amanizw.com"

# No build step required; this is a static site. Deploy by connecting the repo or drag-and-drop the folder to Netlify.